#!/usr/bin/env python3
import argparse
import sys


def is_prime(n):
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d = n - 1
    shifts = 0
    while d % 2 == 0:
        shifts += 1
        d //= 2
    for a in (2, 325, 9375, 28178, 450775, 9780504, 1795265022):
        if a % n == 0:
            continue
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(shifts - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def reverse_bits(value, bits):
    result = 0
    for _ in range(bits):
        result = result << 1 | value & 1
        value >>= 1
    return result


def find_psi(modulus, degree):
    order = 2 * degree
    if (modulus - 1) % order:
        raise ValueError("modulus must be 1 modulo 2N")
    exponent = (modulus - 1) // order
    for base in range(2, modulus):
        psi = pow(base, exponent, modulus)
        if pow(psi, degree, modulus) == modulus - 1:
            return psi
    raise ValueError("no primitive 2N-th root found")


def array(name, ty, values, visibility):
    rows = []
    for start in range(0, len(values), 8):
        rows.append("    " + ", ".join(map(str, values[start : start + 8])) + ",")
    return f"{visibility} const {name}: [{ty}; {len(values)}] = [\n" + "\n".join(rows) + "\n];"


def generate(bits, degree, modulus, name, visibility):
    if not degree or degree & (degree - 1):
        raise ValueError("degree must be a power of two")
    if not is_prime(modulus):
        raise ValueError("modulus must be prime")
    if bits == 32 and 2 * modulus >= 1 << 31:
        raise ValueError("32-bit AVX2 kernel requires 2q < 2^31")
    if bits == 64 and modulus >= 1 << 62:
        raise ValueError("64-bit kernel requires q < 2^62")

    psi = find_psi(modulus, degree)
    psi_inv = pow(psi, -1, modulus)
    log_n = degree.bit_length() - 1
    forward = [pow(psi, reverse_bits(i, log_n), modulus) for i in range(degree)]
    inverse = [pow(psi_inv, reverse_bits(i, log_n), modulus) for i in range(degree)]
    radix = 1 << bits
    ty = f"u{bits}"
    shoup = [value * radix // modulus for value in forward]
    inv_shoup = [value * radix // modulus for value in inverse]
    n_inv = pow(degree, -1, modulus)
    q_inv_neg = -pow(modulus, -1, radix) % radix
    r2 = pow(2, 2 * bits, modulus)
    ring = f"Ring{bits}"

    parts = [
        "// @generated by scripts/paramgen.py; do not edit.",
        f"use negacyclic_rings::{ring};",
        "",
        array("NTT_TABLE", ty, forward, visibility),
        array("NTT_TABLE_SHOUP", ty, shoup, visibility),
        array("INV_NTT_TABLE", ty, inverse, visibility),
        array("INV_NTT_TABLE_SHOUP", ty, inv_shoup, visibility),
        "",
        f"{visibility} const {name}: {ring}<{degree}> = {ring} {{",
        f"    q: {modulus},",
        f"    q_inv_neg: {q_inv_neg},",
        f"    r2: {r2},",
        "    ntt_table: NTT_TABLE,",
        "    ntt_table_shoup: NTT_TABLE_SHOUP,",
        "    inv_ntt_table: INV_NTT_TABLE,",
        "    inv_ntt_table_shoup: INV_NTT_TABLE_SHOUP,",
        f"    n_inv: {n_inv},",
        f"    n_inv_shoup: {n_inv * radix // modulus},",
        "};",
    ]
    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate one negacyclic NTT parameter module")
    parser.add_argument("--bits", type=int, choices=(32, 64), required=True)
    parser.add_argument("--degree", type=int, required=True)
    parser.add_argument("--modulus", type=int, required=True)
    parser.add_argument("--name", default="RING")
    parser.add_argument("--visibility", choices=("pub", "pub(crate)"), default="pub")
    parser.add_argument("--output")
    args = parser.parse_args()
    try:
        source = generate(args.bits, args.degree, args.modulus, args.name, args.visibility)
    except ValueError as error:
        parser.error(str(error))
    if args.output:
        with open(args.output, "w", encoding="utf-8") as output:
            output.write(source)
    else:
        sys.stdout.write(source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
